// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AdsAssetUpdateData, AdsAssetUpdateResponses, AdsCreateData, AdsCreateResponses, AdsDestroyData, AdsDestroyErrors, AdsDestroyResponses, AdsListData, AdsListResponses, AdsRetrieveData, AdsRetrieveResponses, HealthRetrieveData, HealthRetrieveErrors, HealthRetrieveResponses, LoginCreateData, LoginCreateErrors, LoginCreateResponses, LoginDestroyData, LoginDestroyResponses, LoginRetrieveData, LoginRetrieveResponses, TonesListData, TonesListResponses, VideosCreateData, VideosCreateResponses, VideosDestroyData, VideosDestroyErrors, VideosDestroyResponses, VideosListData, VideosListResponses, VideosReprocessCreateData, VideosReprocessCreateErrors, VideosReprocessCreateResponses, VideosRetrieveData, VideosRetrieveErrors, VideosRetrieveResponses, VideosScenesListData, VideosScenesListErrors, VideosScenesListResponses, VideosSlotsListData, VideosSlotsListErrors, VideosSlotsListResponses, VideosSlotsUpdateData, VideosSlotsUpdateErrors, VideosSlotsUpdateResponses, VideosStatusRetrieveData, VideosStatusRetrieveErrors, VideosStatusRetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The ad catalog matched against each scene.
 */
export const adsList = <ThrowOnError extends boolean = false>(options?: Options<AdsListData, ThrowOnError>): RequestResult<AdsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AdsListResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/ads',
    ...options
});

/**
 * The ad catalog matched against each scene.
 */
export const adsCreate = <ThrowOnError extends boolean = false>(options: Options<AdsCreateData, ThrowOnError>): RequestResult<AdsCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<AdsCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/ads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an ad
 *
 * Removes the ad from the catalog. Does not remove the stored asset file.
 */
export const adsDestroy = <ThrowOnError extends boolean = false>(options: Options<AdsDestroyData, ThrowOnError>): RequestResult<AdsDestroyResponses, AdsDestroyErrors, ThrowOnError> => (options.client ?? client).delete<AdsDestroyResponses, AdsDestroyErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/ads/{id}',
    ...options
});

/**
 * The ad catalog matched against each scene.
 */
export const adsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AdsRetrieveData, ThrowOnError>): RequestResult<AdsRetrieveResponses, unknown, ThrowOnError> => (options.client ?? client).get<AdsRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/ads/{id}',
    ...options
});

/**
 * Replace an ad's creative asset
 *
 * Uploads (or replaces) the video/overlay file previewed in the editor.
 */
export const adsAssetUpdate = <ThrowOnError extends boolean = false>(options: Options<AdsAssetUpdateData, ThrowOnError>): RequestResult<AdsAssetUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<AdsAssetUpdateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/ads/{id}/asset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness probe
 *
 * Returns 503 with the connection error if Postgres is unreachable.
 */
export const healthRetrieve = <ThrowOnError extends boolean = false>(options?: Options<HealthRetrieveData, ThrowOnError>): RequestResult<HealthRetrieveResponses, HealthRetrieveErrors, ThrowOnError> => (options?.client ?? client).get<HealthRetrieveResponses, HealthRetrieveErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/health',
    ...options
});

/**
 * Log out
 *
 * Session login/logout. POST is the only public method — it is how you get a session.
 */
export const loginDestroy = <ThrowOnError extends boolean = false>(options?: Options<LoginDestroyData, ThrowOnError>): RequestResult<LoginDestroyResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<LoginDestroyResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/login',
    ...options
});

/**
 * Who am I
 *
 * Session login/logout. POST is the only public method — it is how you get a session.
 */
export const loginRetrieve = <ThrowOnError extends boolean = false>(options?: Options<LoginRetrieveData, ThrowOnError>): RequestResult<LoginRetrieveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<LoginRetrieveResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/login',
    ...options
});

/**
 * Log in and get a session cookie
 *
 * Session login/logout. POST is the only public method — it is how you get a session.
 */
export const loginCreate = <ThrowOnError extends boolean = false>(options: Options<LoginCreateData, ThrowOnError>): RequestResult<LoginCreateResponses, LoginCreateErrors, ThrowOnError> => (options.client ?? client).post<LoginCreateResponses, LoginCreateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/login',
    ...options
});

/**
 * Existing tones to pick from when tagging a scene or an ad's target_tone.
 */
export const tonesList = <ThrowOnError extends boolean = false>(options?: Options<TonesListData, ThrowOnError>): RequestResult<TonesListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<TonesListResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/tones',
    ...options
});

/**
 * List videos uploaded by the current user
 */
export const videosList = <ThrowOnError extends boolean = false>(options?: Options<VideosListData, ThrowOnError>): RequestResult<VideosListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<VideosListResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos',
    ...options
});

/**
 * Upload a video and queue the pipeline
 *
 * Send exactly one of `file` (multipart) or `source_url` (JSON). Returns immediately — all heavy work happens in a Celery worker. Poll `/videos/{uuid}/status` for progress.
 */
export const videosCreate = <ThrowOnError extends boolean = false>(options?: Options<VideosCreateData, ThrowOnError>): RequestResult<VideosCreateResponses, unknown, ThrowOnError> => (options?.client ?? client).post<VideosCreateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a video
 *
 * Removes the video and its scenes. Does not remove the stored file/keyframes.
 */
export const videosDestroy = <ThrowOnError extends boolean = false>(options: Options<VideosDestroyData, ThrowOnError>): RequestResult<VideosDestroyResponses, VideosDestroyErrors, ThrowOnError> => (options.client ?? client).delete<VideosDestroyResponses, VideosDestroyErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}',
    ...options
});

/**
 * One video, with a link to its source file
 *
 * What the editor loads on a cold open. `/status` is the same minus `file_url`.
 */
export const videosRetrieve = <ThrowOnError extends boolean = false>(options: Options<VideosRetrieveData, ThrowOnError>): RequestResult<VideosRetrieveResponses, VideosRetrieveErrors, ThrowOnError> => (options.client ?? client).get<VideosRetrieveResponses, VideosRetrieveErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}',
    ...options
});

/**
 * Re-run one or more pipeline stages
 *
 * Re-trigger detect_scenes, transcribe and/or analyze for an existing video, reusing the stored source file, keyframes and scene boundaries instead of restarting the whole pipeline. Explicit opt-in only — at least one stage must be requested.
 */
export const videosReprocessCreate = <ThrowOnError extends boolean = false>(options: Options<VideosReprocessCreateData, ThrowOnError>): RequestResult<VideosReprocessCreateResponses, VideosReprocessCreateErrors, ThrowOnError> => (options.client ?? client).post<VideosReprocessCreateResponses, VideosReprocessCreateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}/reprocess',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Scenes with tags, keyframes and the recommended ad
 *
 * Ordered by scene index. `description`, `tone`, `iab_categories` and the recommendation are filled in by the per-scene analysis tasks.
 */
export const videosScenesList = <ThrowOnError extends boolean = false>(options: Options<VideosScenesListData, ThrowOnError>): RequestResult<VideosScenesListResponses, VideosScenesListErrors, ThrowOnError> => (options.client ?? client).get<VideosScenesListResponses, VideosScenesListErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}/scenes',
    ...options
});

/**
 * The ad plan for this video
 *
 * Ordered by timecode. On the first read the list is drafted from the scenes that have a recommended ad; from then on it is whatever was last PUT here.
 */
export const videosSlotsList = <ThrowOnError extends boolean = false>(options: Options<VideosSlotsListData, ThrowOnError>): RequestResult<VideosSlotsListResponses, VideosSlotsListErrors, ThrowOnError> => (options.client ?? client).get<VideosSlotsListResponses, VideosSlotsListErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}/slots',
    ...options
});

/**
 * Replace the ad plan
 *
 * Send the whole slot list. Anything omitted is deleted. One call therefore covers adding, moving, editing and removing slots, as well as undo.
 */
export const videosSlotsUpdate = <ThrowOnError extends boolean = false>(options: Options<VideosSlotsUpdateData, ThrowOnError>): RequestResult<VideosSlotsUpdateResponses, VideosSlotsUpdateErrors, ThrowOnError> => (options.client ?? client).put<VideosSlotsUpdateResponses, VideosSlotsUpdateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}/slots',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Job progress
 */
export const videosStatusRetrieve = <ThrowOnError extends boolean = false>(options: Options<VideosStatusRetrieveData, ThrowOnError>): RequestResult<VideosStatusRetrieveResponses, VideosStatusRetrieveErrors, ThrowOnError> => (options.client ?? client).get<VideosStatusRetrieveResponses, VideosStatusRetrieveErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/videos/{uuid}/status',
    ...options
});
