// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://10.21.128.92:8022' | (string & {});
};

export type Ad = {
    readonly id: number;
    target_tone?: string | null;
    readonly asset_url: string | null;
    readonly is_embedded: boolean;
    brand: string;
    title: string;
    description: string;
    ad_type: AdTypeEnum;
    iab_categories?: unknown;
    readonly created_at: string;
};

/**
 * Backs the dedicated "replace the creative" action — never exposes the rest of `Ad`.
 */
export type AdAssetRequest = {
    asset: Blob | File;
};

export type AdRequest = {
    target_tone?: string | null;
    brand: string;
    title: string;
    description: string;
    ad_type: AdTypeEnum;
    iab_categories?: unknown;
};

/**
 * One ad placement. `ad` is written as a pk; `ad_detail` is what the editor renders.
 */
export type AdSlot = {
    readonly id: number;
    scene?: number | null;
    ad?: number | null;
    ad_detail: Ad;
    at_seconds: number;
    duration?: number;
    placement?: PlacementEnum;
    is_overlay?: boolean;
    state?: StateEnum;
    score?: number | null;
};

/**
 * One ad placement. `ad` is written as a pk; `ad_detail` is what the editor renders.
 */
export type AdSlotRequest = {
    scene?: number | null;
    ad?: number | null;
    at_seconds: number;
    duration?: number;
    placement?: PlacementEnum;
    is_overlay?: boolean;
    state?: StateEnum;
    score?: number | null;
};

/**
 * * `video` - Video
 * * `overlay` - Overlay
 */
export type AdTypeEnum = 'video' | 'overlay';

export type Health = {
    status: string;
    db: string;
};

export type PaginatedAdList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Ad>;
};

export type PaginatedVideoListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<VideoList>;
};

/**
 * * `pre_roll` - Pre
 * * `mid_roll` - Mid
 * * `post_roll` - Post
 */
export type PlacementEnum = 'pre_roll' | 'mid_roll' | 'post_roll';

export type Scene = {
    index: number;
    start: number;
    end: number;
    readonly keyframe_urls: Array<string>;
    transcript_text?: string;
    description?: string;
    objects_seen?: unknown;
    readonly tone: string;
    iab_categories?: unknown;
    recommended_ad: Ad;
    match_score?: number | null;
    rationale?: string;
    brand_safety_flag?: boolean;
};

/**
 * * `suggested` - Suggested
 * * `accepted` - Accepted
 * * `held` - Held
 * * `rejected` - Rejected
 */
export type StateEnum = 'suggested' | 'accepted' | 'held' | 'rejected';

export type Tone = {
    readonly id: number;
    name: string;
};

export type User = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    email?: string | string;
    /**
     * Staff status
     *
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
};

export type VideoCreateRequest = {
    file?: Blob | File;
    source_url?: string;
    detect_scenes?: boolean;
    transcribe?: boolean;
    analyze?: boolean;
};

/**
 * What POST /videos hands back: the video's public id and the queued Celery job.
 */
export type VideoJob = {
    readonly uuid: string;
    readonly job_id: string;
    readonly status: string;
};

/**
 * Same shape as the detail/status view, plus a direct link to the uploaded source file.
 */
export type VideoList = {
    readonly uuid: string;
    status?: VideoStatusEnum;
    error?: string;
    duration?: number | null;
    width?: number | null;
    height?: number | null;
    has_audio?: boolean | null;
    readonly thumbnail_url: string | null;
    scenes_total?: number;
    scenes_done?: number;
    /**
     * scenes_done counts attempts, so compare it against what actually got tagged —
     * counting untagged scenes alone would report every pending scene as a failure.
     */
    readonly scenes_failed: number;
    readonly progress: string;
    detect_scenes_enabled?: boolean;
    transcribe_enabled?: boolean;
    analyze_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
    readonly file_url: string | null;
};

/**
 * Explicit opt-in only — nothing reruns unless asked for.
 */
export type VideoReprocessRequest = {
    detect_scenes?: boolean;
    transcribe?: boolean;
    analyze?: boolean;
};

export type VideoStatus = {
    readonly uuid: string;
    status?: VideoStatusEnum;
    error?: string;
    duration?: number | null;
    width?: number | null;
    height?: number | null;
    has_audio?: boolean | null;
    readonly thumbnail_url: string | null;
    scenes_total?: number;
    scenes_done?: number;
    /**
     * scenes_done counts attempts, so compare it against what actually got tagged —
     * counting untagged scenes alone would report every pending scene as a failure.
     */
    readonly scenes_failed: number;
    readonly progress: string;
    detect_scenes_enabled?: boolean;
    transcribe_enabled?: boolean;
    analyze_enabled?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * * `pending` - Pending
 * * `processing` - Processing
 * * `done` - Done
 * * `failed` - Failed
 */
export type VideoStatusEnum = 'pending' | 'processing' | 'done' | 'failed';

export type AdWritable = {
    target_tone?: string | null;
    brand: string;
    title: string;
    description: string;
    ad_type: AdTypeEnum;
    iab_categories?: unknown;
};

export type AdRequestWritable = {
    target_tone?: string | null;
    asset?: Blob | File;
    brand: string;
    title: string;
    description: string;
    ad_type: AdTypeEnum;
    iab_categories?: unknown;
};

/**
 * One ad placement. `ad` is written as a pk; `ad_detail` is what the editor renders.
 */
export type AdSlotWritable = {
    scene?: number | null;
    ad?: number | null;
    at_seconds: number;
    duration?: number;
    placement?: PlacementEnum;
    is_overlay?: boolean;
    state?: StateEnum;
    score?: number | null;
};

export type PaginatedAdListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdWritable>;
};

export type PaginatedVideoListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<VideoListWritable>;
};

export type SceneWritable = {
    index: number;
    start: number;
    end: number;
    transcript_text?: string;
    description?: string;
    objects_seen?: unknown;
    iab_categories?: unknown;
    match_score?: number | null;
    rationale?: string;
    brand_safety_flag?: boolean;
};

export type ToneWritable = {
    name: string;
};

export type UserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    email?: string | string;
    /**
     * Staff status
     *
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
};

/**
 * Same shape as the detail/status view, plus a direct link to the uploaded source file.
 */
export type VideoListWritable = {
    status?: VideoStatusEnum;
    error?: string;
    duration?: number | null;
    width?: number | null;
    height?: number | null;
    has_audio?: boolean | null;
    scenes_total?: number;
    scenes_done?: number;
    detect_scenes_enabled?: boolean;
    transcribe_enabled?: boolean;
    analyze_enabled?: boolean;
};

export type VideoStatusWritable = {
    status?: VideoStatusEnum;
    error?: string;
    duration?: number | null;
    width?: number | null;
    height?: number | null;
    has_audio?: boolean | null;
    scenes_total?: number;
    scenes_done?: number;
    detect_scenes_enabled?: boolean;
    transcribe_enabled?: boolean;
    analyze_enabled?: boolean;
};

export type AdsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/ads';
};

export type AdsListResponses = {
    200: PaginatedAdList;
};

export type AdsListResponse = AdsListResponses[keyof AdsListResponses];

export type AdsCreateData = {
    body: AdRequestWritable;
    path?: never;
    query?: never;
    url: '/ads';
};

export type AdsCreateResponses = {
    201: Ad;
};

export type AdsCreateResponse = AdsCreateResponses[keyof AdsCreateResponses];

export type AdsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this ad.
         */
        id: number;
    };
    query?: never;
    url: '/ads/{id}';
};

export type AdsDestroyErrors = {
    /**
     * Unknown ad
     */
    404: unknown;
};

export type AdsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AdsDestroyResponse = AdsDestroyResponses[keyof AdsDestroyResponses];

export type AdsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this ad.
         */
        id: number;
    };
    query?: never;
    url: '/ads/{id}';
};

export type AdsRetrieveResponses = {
    200: Ad;
};

export type AdsRetrieveResponse = AdsRetrieveResponses[keyof AdsRetrieveResponses];

export type AdsAssetUpdateData = {
    body: AdAssetRequest;
    path: {
        /**
         * A unique integer value identifying this ad.
         */
        id: number;
    };
    query?: never;
    url: '/ads/{id}/asset';
};

export type AdsAssetUpdateResponses = {
    200: Ad;
};

export type AdsAssetUpdateResponse = AdsAssetUpdateResponses[keyof AdsAssetUpdateResponses];

export type HealthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthRetrieveErrors = {
    503: Health;
};

export type HealthRetrieveError = HealthRetrieveErrors[keyof HealthRetrieveErrors];

export type HealthRetrieveResponses = {
    200: Health;
};

export type HealthRetrieveResponse = HealthRetrieveResponses[keyof HealthRetrieveResponses];

export type LoginDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type LoginDestroyResponse = LoginDestroyResponses[keyof LoginDestroyResponses];

export type LoginRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginRetrieveResponses = {
    200: User;
};

export type LoginRetrieveResponse = LoginRetrieveResponses[keyof LoginRetrieveResponses];

export type LoginCreateData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginCreateErrors = {
    /**
     * Bad credentials
     */
    401: unknown;
};

export type LoginCreateResponses = {
    200: User;
};

export type LoginCreateResponse = LoginCreateResponses[keyof LoginCreateResponses];

export type TonesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tones';
};

export type TonesListResponses = {
    200: Array<Tone>;
};

export type TonesListResponse = TonesListResponses[keyof TonesListResponses];

export type VideosListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/videos';
};

export type VideosListResponses = {
    200: PaginatedVideoListList;
};

export type VideosListResponse = VideosListResponses[keyof VideosListResponses];

export type VideosCreateData = {
    body?: VideoCreateRequest;
    path?: never;
    query?: never;
    url: '/videos';
};

export type VideosCreateResponses = {
    202: VideoJob;
};

export type VideosCreateResponse = VideosCreateResponses[keyof VideosCreateResponses];

export type VideosDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}';
};

export type VideosDestroyErrors = {
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type VideosDestroyResponse = VideosDestroyResponses[keyof VideosDestroyResponses];

export type VideosRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}';
};

export type VideosRetrieveErrors = {
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosRetrieveResponses = {
    200: VideoList;
};

export type VideosRetrieveResponse = VideosRetrieveResponses[keyof VideosRetrieveResponses];

export type VideosReprocessCreateData = {
    body?: VideoReprocessRequest;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}/reprocess';
};

export type VideosReprocessCreateErrors = {
    /**
     * No stage requested, or detect_scenes was never run
     */
    400: unknown;
    /**
     * Unknown video
     */
    404: unknown;
    /**
     * Video is already processing
     */
    409: unknown;
};

export type VideosReprocessCreateResponses = {
    202: VideoJob;
};

export type VideosReprocessCreateResponse = VideosReprocessCreateResponses[keyof VideosReprocessCreateResponses];

export type VideosScenesListData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}/scenes';
};

export type VideosScenesListErrors = {
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosScenesListResponses = {
    200: Array<Scene>;
};

export type VideosScenesListResponse = VideosScenesListResponses[keyof VideosScenesListResponses];

export type VideosSlotsListData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}/slots';
};

export type VideosSlotsListErrors = {
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosSlotsListResponses = {
    200: Array<AdSlot>;
};

export type VideosSlotsListResponse = VideosSlotsListResponses[keyof VideosSlotsListResponses];

export type VideosSlotsUpdateData = {
    body: Array<AdSlotRequest>;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}/slots';
};

export type VideosSlotsUpdateErrors = {
    /**
     * A slot in the list is invalid
     */
    400: unknown;
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosSlotsUpdateResponses = {
    200: Array<AdSlot>;
};

export type VideosSlotsUpdateResponse = VideosSlotsUpdateResponses[keyof VideosSlotsUpdateResponses];

export type VideosStatusRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/videos/{uuid}/status';
};

export type VideosStatusRetrieveErrors = {
    /**
     * Unknown video
     */
    404: unknown;
};

export type VideosStatusRetrieveResponses = {
    200: VideoStatus;
};

export type VideosStatusRetrieveResponse = VideosStatusRetrieveResponses[keyof VideosStatusRetrieveResponses];
